export type BrandCategory =
  | 'sneakers'
  | 'fashion'
  | 'luxury'
  | 'watches'
  | 'electronics'
  | 'streetwear'
  | 'sportswear'
  | 'footwear'
  | 'accessories';

export interface Brand {
  name: string;
  slug: string;
  color: string;
  logo: string;
  poster?: string;
  categories: BrandCategory[];
}

export const BRAND_LOGOS: Brand[] = [
  {
    name: 'Zara',
    slug: 'zara',
    color: '#000000',
    logo: '/images/brand-logos/zara.png',
    poster: '/images/brand-posters/zara.png',
    categories: ['fashion'],
  },
  {
    name: 'YSL',
    slug: 'ysl',
    color: '#000000',
    logo: '/images/brand-logos/ysl.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Yeezy',
    slug: 'yeezy',
    color: '#F3371F',
    logo: '/images/brand-logos/yeezy.png',
    categories: ['sneakers', 'streetwear'],
  },
  {
    name: 'Y-3',
    slug: 'y-3',
    color: '#111111',
    logo: '/images/brand-logos/y3.png',
    categories: ['luxury', 'streetwear', 'fashion'],
  },
  {
    name: 'Versace',
    slug: 'versace',
    color: '#E8BB2E',
    logo: '/images/brand-logos/versace.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Vans',
    slug: 'vans',
    color: '#BA0C2F',
    logo: '/images/brand-logos/vans.png',
    categories: ['sneakers', 'streetwear'],
  },
  {
    name: 'Valentino',
    slug: 'valentino',
    color: '#E4002B',
    logo: '/images/brand-logos/valentino.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Vacheron Constantin',
    slug: 'vacheron-constantin',
    color: '#2B2B2B',
    logo: '/images/brand-logos/vacheronconstantin.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Under Armour',
    slug: 'under-armour',
    color: '#000000',
    logo: '/images/brand-logos/underarmour.png',
    categories: ['sportswear'],
  },
  {
    name: 'Tom Ford',
    slug: 'tom-ford',
    color: '#262624',
    logo: '/images/brand-logos/tomford.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Tissot',
    slug: 'tissot',
    color: '#E11A27',
    logo: '/images/brand-logos/tissot.png',
    categories: ['watches'],
  },
  {
    name: 'Tag Heuer',
    slug: 'tag-heuer',
    color: '#003224',
    logo: '/images/brand-logos/tagheuer.png',
    categories: ['watches', 'luxury'],
  },
  {
    name: 'Supreme',
    slug: 'supreme',
    color: '#ED1C24',
    logo: '/images/brand-logos/supreme.png',
    categories: ['streetwear'],
  },
  {
    name: 'Stüssy',
    slug: 'stussy',
    color: '#000000',
    logo: '/images/brand-logos/stussy.png',
    categories: ['streetwear'],
  },
  {
    name: 'Skechers',
    slug: 'skechers-logo',
    color: '#003580',
    logo: '/images/brand-logos/skecherslogo.png',
    categories: ['footwear'],
  },
  {
    name: 'Skechers',
    slug: 'skechers',
    color: '#003580',
    logo: '/images/brand-logos/skechers.png',
    categories: ['footwear'],
  },
  {
    name: 'Seiko',
    slug: 'seiko',
    color: '#002C5F',
    logo: '/images/brand-logos/seiko.png',
    categories: ['watches'],
  },
  {
    name: 'Samsung',
    slug: 'samsung',
    color: '#1428A0',
    logo: '/images/brand-logos/samsung.png',
    categories: ['electronics'],
  },
  {
    name: 'Rolex',
    slug: 'rolex',
    color: '#006039',
    logo: '/images/brand-logos/rolex.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Reebok',
    slug: 'reebok',
    color: '#06080A',
    logo: '/images/brand-logos/reebok.png',
    categories: ['sportswear', 'sneakers'],
  },
  {
    name: 'Ray-Ban',
    slug: 'ray-ban',
    color: '#E31837',
    logo: '/images/brand-logos/rayban.png',
    categories: ['accessories'],
  },
  {
    name: 'Ralph Lauren',
    slug: 'ralph-lauren',
    color: '#041E42',
    logo: '/images/brand-logos/ralphlauren.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Rado',
    slug: 'rado',
    color: '#1A1A1A',
    logo: '/images/brand-logos/rado.png',
    categories: ['watches'],
  },
  {
    name: 'Puma',
    slug: 'puma',
    color: '#E6312A',
    logo: '/images/brand-logos/puma.png',
    categories: ['sportswear', 'sneakers'],
  },
  {
    name: 'Prada',
    slug: 'prada',
    color: '#000000',
    logo: '/images/brand-logos/prada.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Patek Philippe',
    slug: 'patek-philippe',
    color: '#544634',
    logo: '/images/brand-logos/patekphilippe.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Palm Angels',
    slug: 'palm-angels',
    color: '#000000',
    logo: '/images/brand-logos/palmangels.png',
    categories: ['streetwear'],
  },
  {
    name: 'Onitsuka Tiger',
    slug: 'onitsuka-tiger',
    color: '#E8112D',
    logo: '/images/brand-logos/onitsukatiger.png',
    categories: ['sneakers', 'sportswear'],
  },
  {
    name: 'Omega',
    slug: 'omega',
    color: '#C41230',
    logo: '/images/brand-logos/omega.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Off-White',
    slug: 'off-white',
    color: '#000000',
    logo: '/images/brand-logos/offwhite.png',
    categories: ['streetwear', 'luxury'],
  },
  {
    name: 'Oakley',
    slug: 'oakley',
    color: '#000000',
    logo: '/images/brand-logos/oakley.png',
    categories: ['accessories', 'sportswear'],
  },
  {
    name: 'Nike',
    slug: 'nike',
    color: '#000000',
    logo: '/images/brand-logos/nike.png',
    categories: ['sportswear', 'sneakers'],
  },
  {
    name: 'New Balance',
    slug: 'new-balance',
    color: '#E21837',
    logo: '/images/brand-logos/newbalance.png',
    categories: ['sneakers'],
  },
  {
    name: 'Montblanc',
    slug: 'montblanc',
    color: '#000000',
    logo: '/images/brand-logos/montblanc.png',
    categories: ['luxury', 'accessories'],
  },
  {
    name: 'Marshall',
    slug: 'marshall',
    color: '#F2CF6C',
    logo: '/images/brand-logos/marshall.png',
    categories: ['electronics'],
  },
  {
    name: 'Louis Vuitton',
    slug: 'louis-vuitton',
    color: '#49362F',
    logo: '/images/brand-logos/louisvuitton.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Hublot',
    slug: 'hublot',
    color: '#000000',
    logo: '/images/brand-logos/hublot.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'H&M',
    slug: 'h-and-m',
    color: '#E50012',
    logo: '/images/brand-logos/hm.png',
    categories: ['fashion'],
  },
  {
    name: 'Hermès',
    slug: 'hermes',
    color: '#F37021',
    logo: '/images/brand-logos/hermes.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Gucci',
    slug: 'gucci',
    color: '#006747',
    logo: '/images/brand-logos/gucci.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'G-SHOCK',
    slug: 'g-shock',
    color: '#E41F26',
    logo: '/images/brand-logos/gshock.png',
    categories: ['watches', 'sportswear'],
  },
  {
    name: 'Givenchy',
    slug: 'givenchy',
    color: '#000000',
    logo: '/images/brand-logos/givenchy.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Giorgio Armani',
    slug: 'giorgio-armani',
    color: '#00002A',
    logo: '/images/brand-logos/giorgioarmani.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Fossil',
    slug: 'fossil',
    color: '#322F2A',
    logo: '/images/brand-logos/fossil.png',
    categories: ['watches', 'fashion'],
  },
  {
    name: 'Fila',
    slug: 'fila',
    color: '#00205B',
    logo: '/images/brand-logos/fila.png',
    categories: ['sportswear', 'sneakers'],
  },
  {
    name: 'Fendi',
    slug: 'fendi',
    color: '#F9B949',
    logo: '/images/brand-logos/fendi.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Fastrack',
    slug: 'fastrack',
    color: '#ED1C24',
    logo: '/images/brand-logos/fastrack.png',
    categories: ['watches', 'sportswear'],
  },
  {
    name: 'Emporio Armani',
    slug: 'emporio-armani',
    color: '#000000',
    logo: '/images/brand-logos/emporioarmani.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Dolce & Gabbana',
    slug: 'dolce-gabbana',
    color: '#000000',
    logo: '/images/brand-logos/dolcegabbana.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Dior',
    slug: 'dior',
    color: '#000000',
    logo: '/images/brand-logos/dior.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Diesel',
    slug: 'diesel',
    color: '#C8102E',
    logo: '/images/brand-logos/diesel.png',
    categories: ['fashion'],
  },
  {
    name: 'Crocs',
    slug: 'crocs',
    color: '#7EBC00',
    logo: '/images/brand-logos/crocs.png',
    poster: '/images/brand-posters/crocs.png',
    categories: ['footwear'],
  },
  {
    name: 'Converse',
    slug: 'converse',
    color: '#000000',
    logo: '/images/brand-logos/converse.png',
    categories: ['sneakers', 'streetwear'],
  },
  {
    name: 'Citizen',
    slug: 'citizen',
    color: '#000000',
    logo: '/images/brand-logos/citizen.png',
    categories: ['watches'],
  },
  {
    name: 'Chanel',
    slug: 'chanel',
    color: '#000000',
    logo: '/images/brand-logos/chanel.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Casio',
    slug: 'casio',
    color: '#003087',
    logo: '/images/brand-logos/casio.png',
    categories: ['watches', 'electronics'],
  },
  {
    name: 'Cartier',
    slug: 'cartier',
    color: '#9E1030',
    logo: '/images/brand-logos/cartier.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Calvin Klein',
    slug: 'calvin-klein',
    color: '#000000',
    logo: '/images/brand-logos/calvinklein.png',
    categories: ['fashion'],
  },
  {
    name: 'Burberry',
    slug: 'burberry',
    color: '#D63D2C',
    logo: '/images/brand-logos/burberry.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Bose',
    slug: 'bose',
    color: '#1D1D1D',
    logo: '/images/brand-logos/bose.png',
    categories: ['electronics'],
  },
  {
    name: 'Birkenstock',
    slug: 'birkenstock',
    color: '#003261',
    logo: '/images/brand-logos/birkenstock.png',
    categories: ['footwear'],
  },
  {
    name: 'Balmain Paris',
    slug: 'balmain-paris',
    color: '#000000',
    logo: '/images/brand-logos/balmainparis.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Balmain',
    slug: 'balmain',
    color: '#000000',
    logo: '/images/brand-logos/balmain.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Balenciaga',
    slug: 'balenciaga',
    color: '#000000',
    logo: '/images/brand-logos/balenciaga.png',
    categories: ['luxury', 'fashion', 'sneakers'],
  },
  {
    name: 'Audemars Piguet',
    slug: 'audemars-piguet',
    color: '#2B2A29',
    logo: '/images/brand-logos/audemarspiguet.png',
    categories: ['luxury', 'watches'],
  },
  {
    name: 'Asics',
    slug: 'asics',
    color: '#001E62',
    logo: '/images/brand-logos/asics.png',
    categories: ['sportswear', 'sneakers'],
  },
  {
    name: 'Armani Exchange',
    slug: 'armani-exchange',
    color: '#000000',
    logo: '/images/brand-logos/armaniexchange.png',
    categories: ['luxury', 'fashion'],
  },
  {
    name: 'Apple',
    slug: 'apple',
    color: '#555555',
    logo: '/images/brand-logos/apple.png',
    categories: ['electronics'],
  },
  {
    name: 'Amiri Logo',
    slug: 'amiri-logo',
    color: '#000000',
    logo: '/images/brand-logos/amirilogo.png',
    categories: ['fashion'],
  },
  {
    name: 'Amiri',
    slug: 'amiri',
    color: '#000000',
    logo: '/images/brand-logos/amiri.png',
    categories: ['fashion'],
  },
  {
    name: 'Jordan',
    slug: 'jordan',
    color: '#000000',
    logo: '/images/brand-logos/airjordan.png',
    categories: ['sneakers', 'streetwear'],
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    color: '#007FC5',
    logo: '/images/brand-logos/adidas.png',
    categories: ['sportswear', 'sneakers'],
  },
];

export const MAJOR_COLORS = [
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Green', hex: '#008000' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Grey', hex: '#808080' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Beige', hex: '#F5F5DC' },
];
