export { default } from './product-page-master';
export { default as EditorialError } from './editorial-error';
export { default as RelatedProducts } from './related-products';
export { default as ReviewSection } from './review-section';
export { default as VariantDropdown } from './variant-dropdown';
export { default as Gallery } from './gallery';
export { default as ProductPerks } from './product-perks';
export { default as CTAStickyButtons } from './cta-sticky-buttons';
export { useLiveProductMetric } from './use-live-product-metric';
export { getGlobalSlot, getPageSlot } from './time';
export { getProductBySlug, getSimilarProducts } from '@/data/filter-engine';
export { reviews } from './data/reviews';
